import { StyleSheet } from "react-native";

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "stretch",
    backgroundColor: "#2c0033",
    paddingHorizontal: 0,
    paddingVertical: 10,
  },
  title: {
    color: "#fff",
    fontSize: 36,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    textAlign: "center",
    marginBottom: 8,
    textShadowColor: "rgba(0,0,0,0.6)",
    textShadowOffset: { width: 0, height: 10 },
    textShadowRadius: 10,
  },
  subtitle: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  button: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    backgroundColor: "#fff",
    borderRadius: 8,
    marginTop: 24,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(0,0,0,0.3)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonText: {
    color: "#2c0033",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  errorCode: {
    color: "#fff",
    fontSize: 72,
    fontWeight: "900",
    marginBottom: 16,
    textShadowColor: "rgba(0,0,0,0.6)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
  },
  errorTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 12,
  },
  errorSubtitle: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 24,
  },
  postItem: {
    padding: 10,
    borderBottomWidth: 1,
    width: "100%",
    borderBottomColor: "#ccc",
    backgroundColor: "rgba(255,255,255,0.1)",
    marginVertical: 5,
    marginHorizontal: 0,
    borderRadius: 8,
  },
  postTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  postBody: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 14,
    lineHeight: 20,
  },
  inputStyle: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginVertical: 10,
    marginHorizontal: 10,
    fontSize: 16,
    backgroundColor: "#fff",
    width: "auto",
  },
});

// #6d0e74
// #5d0b64
// #4d0754
// #3c0443
// #2c0033
